### ISSUE TITLE
Improve aesthetics of Module UI.

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#127]
Need to figure out border: the port widget interfered with the QFrame's built-in border.

Border is improved. Remaining issues:
- [x] Widget is too long. There's empty space after the name that could be compressed. (#1424)
- [ ] High-res screen issue. (#1453)
- [x] By default modules are still quite big.  (#1424)
- [x] Color of tooltips match module color. This can make them hard to see when module is selected.

**Comment by dcwhite** [comment]
@gduffley This is your issue. Note the age...

**Comment by gduffley** [comment]
@dcwhite I was still but a child when this issue was first submitted

**Comment by dcwhite** [comment]
Tooltips still match module color, but now the background pattern makes them stand out more.

**Comment by jessdtate** [comment]
with the new module sizes, FlipSurfaceNormals, SplitFieldByDomain, and ClipFieldByFunction have the names slightly cut off. ConvertFieldBasis,CalculateFieldData,CalculateFieldGradients, and other similar module length names are all a little too small compared to other modules.

**Comment by dcwhite** [comment]
Thanks. I'll adjust the text size thresholds.

**Comment by jessdtate** [comment]
with the icons hidden, the error indication is also hidden, which can make it hard to tell which is throwing an error.

**Comment by dcwhite** [comment]
I noticed this too...I need to get the "errored module changes red" working again (it's broken currently). I might propagate the status color to the title label as well.
