### ISSUE TITLE
signed packages

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1663]
productbuild should make it easy to created signatures for os x pacakges.  This will allow release on the apple store and such.  Ed should have a certificate to use.

**Comment by dcwhite** [comment]
@jessdtate Any other CIBC products figure this out yet?

**Comment by jessdtate** [comment]
no, but it is still on my wishlist

**Comment by dcwhite** [comment]
@jessdtate has a new certificate. Need to see who wants to figure out how to use it first.

**Comment by dcwhite** [comment]
**Investigation findings (2026-06-12)**

Signed macOS packages allow distribution outside direct download (App Store, Gatekeeper notarization) and remove the 'unidentified developer' warning on install.

**Current state:** The CI packaging step (reusable-build.yml) runs make package / cmake --build --target package to produce a .pkg file, but no signing or notarization steps exist.

**What is needed:**
1. A Developer ID certificate (comments say Jess has one) stored as a GitHub Actions secret
2. productbuild --sign 'Developer ID Installer: ...' to sign the .pkg
3. For macOS 10.15+, notarization is also required: xcrun notarytool submit + xcrun stapler staple
4. The signing identity and Apple ID credentials need to be stored as GitHub Actions secrets (MACOS_CERTIFICATE, MACOS_CERTIFICATE_PWD, APPLE_ID, APPLE_TEAM_ID, etc.)

**GitHub Actions implementation:** Add a 'Sign and notarize' step after the Package step in reusable-build.yml, gated on runner.os == 'macOS' and a secret being present (so unsigned builds still work for forks/PRs).

**Effort:** Small-medium for the CI workflow changes. The main prerequisite is having the certificate loaded into GitHub secrets, which is an admin task.

**Comment by dcwhite** [comment]
## Why this matters more now

Branch `claude/mac-installer-publishing-2435b8` adds a rolling `nightly` prerelease to `mac.yml`: the four macOS `.pkg` installers the nightly already builds get attached to a permanent `releases/tag/nightly` link, and that link is posted to the CI Slack channel alongside the nightly test results.

Until now the installers were Actions artifacts — 90-day expiry, signed-in GitHub account required — so almost nobody hit the Gatekeeper wall. Once there's an anonymous download link, everyone who clicks it does. The release body currently ships the `xattr -dr com.apple.quarantine` workaround as a stopgap.

## Correcting the 2026-06-13 analysis above

That comment's four steps are right as far as they go, but `productbuild --sign` on the `.pkg` is the last 10% of the job, and the "small-medium" estimate follows from that omission. Notarization inspects every Mach-O *inside* the package. `SCIRun.app` ships Qt frameworks, an embedded `Python.framework`, and the entire SCIRun `lib` directory copied into `Contents/Frameworks` — none of it signed. Signing only the installer wrapper gets the submission rejected.

Two certificates are needed, not one, both from the same Developer ID account:

- **Developer ID Application** — the `.app`, its frameworks, and every dylib inside
- **Developer ID Installer** — the `.pkg`

## Where the steps actually have to go

Signing is order-sensitive, and two things in the current build actively destroy signatures:

1. **`install_name_tool` invalidates signatures.** `src/Main/osx_bundle/CMakeLists.txt` (lines 86–118) rewrites install names on `Python.framework` and 14 SCIRun dylibs *after* they are placed in the bundle. Anything signed before that point is signed for nothing. App signing therefore has to run after `macdeployqt` and after every `POST_BUILD` step — a CI step in `reusable-build.yml`, not a CMake `POST_BUILD` command.

2. **`pkgutil --flatten` strips the package signature.** `src/CMake/scripts/repair_package.sh.in` finishes with `pkgutil --expand` → `pkgutil --flatten` to work around the relocatable-bundle problem. A `productbuild --sign` upstream of that gets thrown away. The package has to be signed *after* `repair_package.sh` runs, with `productsign --sign "Developer ID Installer: …" unsigned.pkg signed.pkg`.

So the working order is:

```
build → macdeployqt → install_name_tool fixups
      → codesign the app bundle (inside-out, --options runtime, with entitlements)
      → make package → repair_package.sh
      → productsign the .pkg
      → xcrun notarytool submit --wait
      → xcrun stapler staple
```

The cheap way to do the app-signing step is `macdeployqt -codesign=<identity>`, which signs during a pass already being paid for — relevant given #2664 found macdeployqt running four times per packaging job.

## The hard part

Notarization requires the hardened runtime (`--options runtime`), and embedded Python will not launch under it without entitlements. At minimum:

- `com.apple.security.cs.disable-library-validation` — SCIRun loads its own dylibs out of `Contents/Frameworks`
- `com.apple.security.cs.allow-unsigned-executable-memory` — typically needed by embedded CPython

Getting that combination to both notarize *and* still launch is the multi-day item. The workflow YAML around it is a couple of hours.

## Secrets required

- `MACOS_CERT_P12` — base64 of a `.p12` holding both certificates
- `MACOS_CERT_PASSWORD`
- `MACOS_SIGN_IDENTITY_APP`, `MACOS_SIGN_IDENTITY_INSTALLER` — the identity strings
- Notarization credentials. Prefer an App Store Connect API key (`APPLE_API_KEY_ID`, `APPLE_API_ISSUER_ID`, `APPLE_API_KEY_P8`) over Apple ID + app-specific password: it does not expire and is not tied to one person's account.

CI imports the `.p12` into a throwaway keychain and deletes it afterward. Every signing step must be gated on the secret being non-empty — secrets are unavailable to fork PRs, and an ungated step breaks every outside contribution.

## Blocker

**The certificate.** Jess had one as of 2020 (comment above). Developer ID certificates are valid for 5 years and the Apple Developer Program membership renews annually, so a 2020 certificate is expired. Confirming the account is live and issuing fresh certs is the prerequisite; no workflow code is worth writing before that is settled.

## TODO

- [ ] Confirm the SCI Apple Developer Program membership is current; identify the account holder
- [ ] Issue a *Developer ID Application* certificate and a *Developer ID Installer* certificate
- [ ] Create an App Store Connect API key for notarization
- [ ] Load all of the above into repo secrets (admin task)
- [ ] Add an entitlements plist covering library validation and unsigned executable memory
- [ ] Sign the app bundle in `reusable-build.yml`, after the `install_name_tool` fixups (try `macdeployqt -codesign=` first)
- [ ] Sign the `.pkg` with `productsign` *after* `repair_package.sh`, not before
- [ ] Add `notarytool submit --wait` + `stapler staple`, gated on secrets being present
- [ ] Verify with `spctl -a -vvv -t install` and a download-and-open test on a clean machine
- [ ] Decide the scope: `notarytool --wait` runs 2–10 min per submission, so sign only the nightly release variants, not PR builds
- [ ] Drop the `xattr` workaround from the nightly release notes in `mac.yml` once signing lands
