### ISSUE TITLE
Speed up Clang Travis build

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1768]
It's timing out all the time now. 

Ideas:
- [ ] Stub out non-UI layers, just build UI.
- [ ] Fix more warnings
- [ ] Trim down external dependencies
- [ ] Skip unit tests (let GCC cover this part)
- [ ] Don't build all modules. "Retire" some module stacks from the CI build as they mature, so that new code can always get built right away.

**Comment by dcwhite** [comment]
We should incorporate these ideas after stress testing the github action build.

**Comment by dcwhite** [comment]
Not sure how important this is now that we have longer Github action build time available. It's still useful in theory however.

**Comment by dcwhite** [comment]
**Analysis (2026-06-12)**

The Travis Clang timeout this was filed against no longer exists — CI moved to GitHub Actions. However the underlying concern (build time) is still valid.

The sccache + Superbuild externals caching added for #1487 directly addresses this: on cache hits, the Superbuild step (1-2 hours) is skipped entirely, and sccache short-circuits recompilation of unchanged translation units. The checklist items 'trim external dependencies' and 'skip unit tests' are now handled through the `build-testing` and `build-with-python` inputs on reusable-build.yml.

Suggest reviewing whether this can be closed now that #1487 caching is in place.

**Comment by dcwhite** [comment]
**Correction + analysis (2026-08-05)**

### First, retracting my 2026-06-13 comment

That comment claimed the sccache + Superbuild externals caching from #1487 "is in place" and that this issue could be closed on that basis. **That was wrong.** There is no caching in CI at all — the string `cache` does not appear anywhere in `.github/workflows/` (no `sccache`, no `ccache`, no `actions/cache`). All of the caching work is still open and unmerged: #2520, #2576, #2626, #2627, #2628.

The two claims in that comment that *were* correct: the Travis Clang timeout this issue was filed against no longer exists (CI is on GitHub Actions), and the `build-testing` / `build-with-python` inputs on `reusable-build.yml` do exist.

### Triage of the original checklist

- [ ] ~~**Stub out non-UI layers, just build UI**~~ — obsolete, and superseded in the opposite direction. `reusable-build.yml` has a `variant: headless` that skips `ADD_SUBDIRECTORY(Interface)` entirely. Building the UI against a stubbed Core would mean maintaining a fake Core; all cost, no benefit.
- [ ] **Fix more warnings** — real work, but it is a log-signal issue, not a build-time issue. Measured below; routed to #2432.
- [ ] **Trim down external dependencies** — still the live idea, and now much better tracked elsewhere: #2629 (Boost built twice by two build systems; 29 of 37 libraries unused), #2630 (Boost clone alone is 5m10s — 172 submodules, full history, moving-branch "tag"), #2642 (VTK vendors zlib/freetype/glew that SCIRun also builds).
- [x] **Skip unit tests** — done. `build-testing` defaults to `false` on `reusable-build.yml`; only the headless jobs enable it.
- [ ] **Don't build all modules / "retire" mature module stacks** — recommend against. It trades guaranteed compile coverage for minutes, in a tree where the module factory generates code, so a retired stack rots silently. The modern form of the same instinct is #1889 (unity/PCH builds), which gets the speedup without dropping coverage.

### Measured warning data

Since "fix more warnings" sat as an unquantified checkbox since 2018, here are numbers. Source: full log of the `ccpp.yml` run for `docs(readme): modernize CI status badges (#2585)` (run 30968945518, 2026-08-05), 19.5 MB covering all matrix jobs. Counts are of warnings carrying a `-W` flag.

| metric | value |
|---|---|
| warning emissions | 4,892 |
| unique warning sites | 438 |
| **amplification factor** | **~11x** |
| warning-related log volume | ~2.7 MB (~14% of the log) |

The amplification is the whole story: 438 real problems are being reprinted 4,892 times because they live in headers that get included across many translation units. The compile-time cost of emitting them is negligible against a multi-hour build (though not literally zero — 1,260 of the emissions drag a template instantiation context that GCC has to walk and format). The cost that matters is that a reviewer cannot find a genuine new warning in that.

**Worst offenders, by emission count:**

| emissions | site |
|---|---|
| 743 | `Eigen/src/Core/arch/NEON/PacketMath.h:1716` `-Wclass-memaccess` |
| 743 | `Eigen/src/Core/arch/NEON/PacketMath.h:1671` `-Wclass-memaccess` |
| 176 | Boost `is_auto_ptr.hpp` + friends, `-Wdeprecated-declarations` |
| 150 | `Eigen/src/Core/PlainObjectBase.h:504` `-Wmaybe-uninitialized` |
| 66 | `Core/Persistent/Persistent.h:310` `-Wmaybe-uninitialized` |
| 144 | `Core/Datatypes/Legacy/Field/LatVolMesh.h:1039-1041` `-Wmisleading-indentation` (3 sites) |
| 216 | `Core/Datatypes/Legacy/Field/ImageMesh.h` `-Wmisleading-indentation` (6 sites) |
| 180 | `Core/Datatypes/Legacy/Field/ScanlineMesh.h` `-Wmisleading-indentation` (5 sites) |

Two lines of vendored Eigen produce 1,486 emissions — 24% of every warning in the run.

**By flag:**

```
1548  -Wsign-compare
1486  -Wclass-memaccess
 972  -Wmisleading-indentation
 510  -Wmaybe-uninitialized
 156  -Wdeprecated-declarations
  42  -Wpragmas
  40  -Wunused-result
```

**The split that determines what to do about it:**

- **2,080 emissions (43%) come from externals and system headers** — Eigen, Boost, GLM, Python. Not our code, not our bugs, and not fixable by us.
- **2,952 emissions from 383 unique sites in `src/`** — ours, ~7.7x amplified, heavily concentrated in the Legacy mesh headers.

The external 43% is suppressible with `-isystem`, with no source edits. That fix is already written in the tree and commented out — `src/CMakeLists.txt:576`:

```cmake
#INCLUDE_DIRECTORIES(SYSTEM ${SCI_BOOST_INCLUDE})
```

Every external (Eigen, GLM, spdlog, zlib, Qwt, Cleaver) is pulled in through the plain `INCLUDE_DIRECTORIES` block at `src/CMakeLists.txt:566-574`; the single `SYSTEM` variant above is disabled. This matches the original note on #2432 from 2023 — "It shouldn't apply to externals anyway."

### Disposition

Nothing on this checklist survives that is not tracked better somewhere else:

- build time -> #1487, and specifically #2629 / #2630 for the dependency trimming
- caching -> #2520 / #2576 / #2626 / #2627 / #2628
- warnings -> #2432 (the `-isystem` half; data above cross-posted there)

Recommend closing this as superseded by #1487. The 2018 framing (a Travis Clang timeout) describes infrastructure that no longer exists.

**Comment by dcwhite** [comment]
Own-code warning cleanup is now tracked in #2647 (383 unique sites, 2,952 emissions). The externals half stays on #2432. That closes out the routing for the "fix more warnings" checkbox above.

**Comment by dcwhite** [comment]
Closing as superseded by #1487.

The Travis Clang timeout this was filed against in 2018 describes infrastructure that no longer exists. Every surviving idea from the checklist is tracked better elsewhere:

- build time / dependency trimming -> #1487, specifically #2629 and #2630
- CI caching -> #2520, #2576, #2626, #2627, #2628
- warnings (externals) -> #2432
- warnings (our code) -> #2647
- skip unit tests -> already done, `build-testing` defaults to false on `reusable-build.yml`

The two ideas not carried forward are recorded in the triage comment above: stubbing non-UI layers (superseded by the `headless` variant) and retiring module stacks from CI (trades compile coverage for minutes; #1889 is the better form).
