### ISSUE TITLE
Fix issues with Qt 5 build

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1774]
- [ ] Code changes (connect() interface for instance) (#1993)
- [x] Graphics/OpenGL issues (follow SCIInstitute/Seg3D#150 and SCIInstitute/Seg3D#119 on Windows, not Mac
- [ ] Modules stack on top of each other until you hover over(#1982)
- [x] New in 5.12: white objects in ViewScene (#1857)
- [x] ViewScene breaks when closed.
- [ ] All subwindows briefly appear on start-up. (#1981)
- [ ] Centering in network editor is messed up. (#1982)
- [ ] Widget stylesheet problems: LineEdit, SpinBox, Label are all white background. (#1983)
- [ ] ShowFieldGlyphs UI needs resizing (esp. on Windows)(#1983)
- [x] Investigate notes not working
- [ ] Widget selection in ViewScene doesn't work on 10.14 (#1996)

**Comment by dcwhite** [comment]
https://forum.qt.io/topic/92949/migration-from-qglwidget-to-qopenglwidget

**Comment by dcwhite** [comment]
Need to break out subissues here. The VS crashes can be investigated on Windows now, in debug mode.

**Comment by dcwhite** [comment]
Closing since all sub-issues are broken out into their own issues.
