### ISSUE TITLE
Prerequisites for EMBB smart widget meta-issue

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2051]
Following #1497.
- [x] Transform class improvements, with tests
- [x] New bounding box primitive, with tests
- [ ] New mesh function for above, with lots of tests
- [x] VS/SRInterface infrastructure to support fancier widget interactions
- [ ] BoundingBoxWidget v2.0
- [ ] Many test networks (and scripts?)

**Comment by dcwhite** [comment]
@RubioJr9 OK, next up is the mesh function (or separate algo class) to produce the oriented bbox for each type of mesh. The more test code the better!
