### ISSUE TITLE
ShowField module porting, part 3: implement more features of the v4 GUI

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#270]
Continuation of #158. 
- [x] Nodes as spheres is functional but not hooked up.
- [ ] vector data (normalized) creates RGB colors, (#884)
- [ ] the principle Eigen Vector (normalized) of tensor data also creates RBG colors. (#884)
- [x] Auto-execute (#700)
- [x] Edges as cylinders (in progress, #877)

**Comment by dcwhite** [comment]
Closed by https://github.com/SCIInstitute/SCIRun/commit/0a4427b365d75fa9284255a41c1545080d57ac79
