### ISSUE TITLE
ViewScene delivery in I

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#441]
- [x] Async port (see #439)
- [x] More robust colormapping
- [x] More robust rendering

Pushed/future issues:
- [x] Basic object selection (display toggle, #452)
- [x] Tensor eigenvalues (#531)
- [x] Hotkey for Autoview (#529)
- [x] Text rendering (#530)
