### ISSUE TITLE
ViewScene delivery in O

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#536]
Most likely:
- [ ] Basic object selection (display toggle, #452)

More: 
- [ ] Tensor eigenvalues (#531) (moved to P+)
- [x] Hotkey for Autoview (#529)
- [ ] Text rendering (#530) (moved to P+)

**Comment by aylakhan** [comment]
@cbrightsci - please update this issue!

**Comment by dcwhite** [comment]
We can close it, it's covered by the subissues.
