### ISSUE TITLE
More module porting: torso-tank-bem

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#586]
- [x]  EditMeshBoundingBox #707 (not as important to the basic function of the network)
- [x]  BuildBEMatrix #712 (should be rethought to avoid properties)
- [ ]  SetFieldOrMeshStringProperty (see BuildBEMatrix) NOT NEEDED 
- [x]  MapFieldDataFromSourceToDestination (or another mapping module)
- [x]  SwapFieldDataWithMatrixEntries #713 (can use SetFieldData)
- [x]  Other Modules in forward_problem network (issue #539)
- [ ] ReportColumnMatrixMisfit NOT NEEDED

**Comment by dcwhite** [comment]
Modules are there but either not done or have numerical issues:
- [ ] BuildBE numbers are off
- [ ] EMBB needs widget support and auto-execute

**Comment by dcwhite** [comment]
Still needs work.
