### ISSUE TITLE
More module porting: activation-based-fem

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#590]
- [x] ConvertFieldBasis #680 DONE, except mapping matrix section, needs heavy Sparse matrix code conversion
- [x]  CalculateDistanceToField
- [x]  InterfaceWithTetgen #709
- [x]  RefineMesh #681 (we can save out the geometry after this step as a work around, we wouldn't need CalculateDistanceToField, or InterfaceWithTetgen either)
- [x]  SetFieldDataToConstantValue (can use CreateFieldData)
- [x]  BuildMatrixOfSurfaceNormals #710 (there is another method which wouldn't need this, but would need ScaleMeshAndFieldData.  We could also save out this geometry)
- [x]  BuildMappingMatrix #711 (there is another method which wouldn't need this)
- [x]  ApplyFEMCurrentSource #708 (there is another method which wouldn't need this)
- [x]  other modules in issue #539

I should note that this network may not be the best way to solve this problem.
