### ISSUE TITLE
Redo how transparency is done

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#813]
The way transparency works at the moment has taken up a lot of the CPU. Come up with a different way for the transparency to work.

- [x] create lists of object in different directions. #814 
- [x] Base list being rendered on the direction the camera is facing. #815 
- [x] Get Transparency to look better with basic objects. #818
- [x] Edges aren't rendering correctly with new order. #820
- [x] Test with networks for crashes.

**Comment by cbrightsci** [comment]
[] create lists of object in different directions. #814 
[] Base list being rendered on the direction the camera is facing. #815

**Comment by cbrightsci** [comment]
The new transparency is implemented. It doesn't crash on networks and is faster.
