### ISSUE TITLE
CreateStandardColorMap improvements

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#898]
- [x] Extract changing implementation into strategy objects, rather than switch on the name.
- [ ] Add more of the built-in colormaps from v4. (#1348)
- [ ] Improve performance of GUI; sliding the sliders back and forth is sluggish. A lot of extra objects are created and destroyed. (#1349)
- [x] Move list of available color maps out of GUI layer. Right now it's hard-coded in the combo box settings.
- [ ] Pass alpha parameter (#1201)

**Comment by dcwhite** [comment]
Closing this issue, 3 other sub-parts have their own issue now.
