### ISSUE TITLE
IBBM networks and modules

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#918]
IBBM/Bioelectricity/Forward_Problems/Dipole_Source/DipoleSourceExample.srn
- [ ] ShowAndEditDipoles #991 
- [x] GenerateSinglePointProbeFromField (possible work around) #992

IBBM/Bioelectricity/Forward_Problems/rabbit_heart/bem_tank_forward.srn
- [ ] EditMeshBoundingBox (full functionality) #807

IBBM/Bioelectricity/Tissue_Modeling/Slab_Models/Display_PhiE_data.srn
IBBM/Bioelectricity/Tissue_Stimulation/defib_fem_evaluate.srn (may want to skip)
- [x] InterfaceWithMatlab #927
- [x] Bundles (ReadBundle/GetFieldFromBundle)

IBBM/Bioelectricity/Inverse_Problems/dipole_localization/optimize_dipole.srn
   (This network is challenging and might be too hard to get done before the workshop)
- [x] GeneratePointSamplesFromField(OrWidget) #994
- [ ] OptimizeDipole (this is the hard part) #997
- [x] SolveMinNormLeastSqSystem (only used with OptimizeDipole)
- [x] ReportColumnMatrixMisfit (only used with OptimizeDipole) #996
- [x] ConvertHexVolToTetVol
- [x] ShowFieldGlyphs #978

IBBM/Bioelectricity/Inverse_Problems/dipole_localization/dipole_forward.srn
	same as DipoleSourceExample.srn
IBBM/Bioelectricity/Inverse_Problems/greensite.srn
- [x] InterfaceWithMatlab #927

IBBM/Bioelectricity/Inverse_Problems/wbp.srn
- [x] InterfaceWithMatlab #927
- [ ] ShowString #530

IBBM/Numerical_Methods/Lab3/cube_simulation.srn
- [ ] EditMeshBoundingBox #807
- [x] AddLinkedNodesToLinearSystem (kind of optional) #993

IBBM/Image_Processing/Lab3/Registration_Network.srn
- [x] RegisterWithCorrespondences #969

IBBM/Scientific_Visualization/Lab4/tensor_view.srn
- [x] ShowFieldGlyphs (tensors) #978
- [x] GetSliceFromStructuredFieldByIndices #995

IBBM/Scientific_Visualization/Lab4/view_fibers.srn
- [x] ShowFieldGlyphs (vectors) #978
- [x] GetSliceFromStructuredFieldByIndices #995

IBBM/Scientific_Visualization/Lab4/streamline.srn
- [x] Bundles(ReadBundle/GetFieldFromBundle)
- [x] GeneratePointSamplesFromField(OrWidget) #994

IBBM/Scientific_Visualization/Lab1/ibbm_lab_data/scirun/data_visualization.srn
- [x] ClipVolumeByIsovalue #922

IBBM/Scientific_Visualization/Lab2/IsosurfacingModule/Isosurfacing_Cube.srn
- [x] GenerateSinglePointProbeFromField (not really needed) #992

IBBM/Scientific_Visualization/Lab2/IsosurfacingModule/Isosurfacing_Hip.srn
- [x] ExtractIsosurfaces

ViewScene Features:
- [ ] widgets
- [x] turning objects on and off
- [ ] clipping
- [ ] multiple windows/locking rotation together
- [x] glyphs
- [x] colormaps with text

**Comment by aylakhan** [comment]
Thanks Jess! Are there any ViewScene features that you need?

**Comment by dcwhite** [comment]
Thanks for this great list!

**Comment by jessdtate** [comment]
we will show off as many features that we can get implemented.  some of the viewscene features that are more important:
widgets
turning objects on and off
clipping
multiple windows/locking rotation together
glyphs
colormaps with text

**Comment by jessdtate** [comment]
Also, some of these networks may not be worth getting working in time.  We can discuss which ones would give us the most bang for buck.

**Comment by aylakhan** [comment]
Yes please - having ViewScene features on the list will be helpful. Let's find a time to meet this week with @dcwhite, @cbrightsci.

**Comment by lizutah** [comment]
@moritzdannhauer - do you want to add some potential BrainStimulator demos and required modules to the list?

**Comment by moritzdannhauer** [comment]
Yes, some new ones, but I dont know if we can show off all of them in the demos since some of them might need some computation time. But maybe for a simplified model
1) ElectrodeCoilSetup: I need some functionality from MarchingCube (Dan knows what I mean) 
2) InterfaceToCleaver2 (after Shankar fixed the bug): Talked to Brig about it today. Which features are needed?
3) CreateElectrodeCoilPrototype (i am gonna implement that) - should not be too hard
4) GenerateStreamLines (needs to become multi-threaded)
5) For ECoG stimulation I am planning a module that computes a smooth convex hull of a segmentation (brain) - the collaborators in Freiburg will help me with it
6) DBS capabilities: gonna talk to Chris about it

This is a long list and a lot of work. That is all I envision for BrainStimulator and of course not all of it needs to be ready for IBBM

**Comment by aylakhan** [comment]
@moritzdannhauer @dcwhite  is there a GitHub issue for required marching cube functionality? If not, someone please create it.

**Comment by dcwhite** [comment]
#922

**Comment by dcwhite** [comment]
SCIRun 4 versions of the networks above can be found at https://github.com/SCIInstitute/SCIRun-Exchange/tree/master/IBBM2014

**Comment by jessdtate** [comment]
I realized I missed a module: GetSliceFromStructuredFieldByIndices for the tensor and fiber visualization

**Comment by dcwhite** [comment]
@jessdtate Here is last year's issue.
